services:
  nginx:
    image: nginx:alpine
    container_name: nginx-uat
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

    restart: unless-stopped

  frontend:
    image: teim123/krisna_air:frontend-uat-1.0.1
    container_name: frontend-uat
    expose:
      - "80"
    restart: unless-stopped

  backend:
    image: teim123/krisna_air:backend-uat-1.0.0
    container_name: backend-uat
    env_file:
      - .env.uat
    expose:
      - "8000"

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: db-uat

    env_file:
      - .env.uat

    volumes:
      -  mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-uat
    environment:
      PMA_HOST: db
      PMA_USER: ka_user
      PMA_PASSWORD: ka_pass
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
